### ISSUE TITLE
Logging support

### ISSUE THREAD

**Issue by AndreLouisCaron** [stogh/ngx_http_auth_pam_module#3]
Hi, and thanks for this awesome NGINX module :-)

I'm trying to get something working and I'm having a hard time debugging this.  When I use the `pamhelper` tool to test things, I get useful output to the standard output, but I can't get NGINX to log anything to its log files from a PAM module.

I'm somewhat new to PAM so correct me if I'm wrong, but it seems like the usual way to do this is to have the conversation function forward `PAM_ERROR_MSG` (and optionally `PAM_TEXT_INFO`) messages to the application log files.

The swtich-case construct in `ngx_auth_pam_talker()` treats these as invalid and the info is lost.  Any chance you would accept a patch that forwards `PAM_ERROR_MSG` messages to NGINX's log files?

**Comment by stogh** [comment]
Merged  patch

**Comment by sbraz** [comment]
Thanks, should we expect a new release soon?

**Comment by stogh** [comment]
I've added the v1.5 tag, so it is out now ... ;)
