### ISSUE TITLE
Environment support is not in Ubuntu packages

### ISSUE THREAD

**Issue by AndreLouisCaron** [stogh/ngx_http_auth_pam_module#4]
Don't take this the wrong way, I understand you may not be the Ubuntu package maintainer for your project :-)

It seems this NGINX module is distributed in Ubuntu's `nginx-extras` package which seems to use a version of this module that doesn't support the PAM environment support for `REQUEST` and `HOST`.

However, looking at your changelog, it seems this was added in 2013.  I'd like to avoid recompiling NGINX from source for my project, so I was wondering if you know how this gets distributed by Ubuntu...

**Comment by stogh** [comment]
It is taken from debian and latest packages use the latest version (1.4 was updated for nginx 1.9.1-1, the Debian changelog is from Fri, 12 Jun 2015)
